before_install:
- sudo chmod +x install-dependencies.sh

install: ./install-dependencies.sh

script:
- export PATH=$PATH:$(pwd)/ballerina-tools-0.970.0-alpha1/bin
- cd src/
- ballerina init
- ballerina test

jdk:
 - oraclejdk8
