# Copyright (c) 2018, WSO2 Inc. (http://wso2.com) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

script:
# Ballerina
- BALLERINA_VERSION="${VERSION:-0.976.1-SNAPSHOT}"
- echo -e "\033[36m${BALLERINA_VERSION}\033[m"

- DISTRIBUTION_NAME=ballerina-platform-$BALLERINA_VERSION
- echo -e "\033[36m${DISTRIBUTION_NAME}\033[m"

- DOWNLOAD_CHANNEL="${CHANNEL:-nightly}"
- echo -e "\033[36m${DOWNLOAD_CHANNEL}\033[m"

- DOWNLOAD_LOCATION="${URL:-https://product-dist.ballerina.io}"
- echo -e "\033[36m${DOWNLOAD_LOCATION}\033[m"

- echo -e "\033[36m$DOWNLOAD_LOCATION/$DOWNLOAD_CHANNEL/$BALLERINA_VERSION/$DISTRIBUTION_NAME.zip\033[m"
- wget $DOWNLOAD_LOCATION/$DOWNLOAD_CHANNEL/$BALLERINA_VERSION/$DISTRIBUTION_NAME.zip

- unzip -q $DISTRIBUTION_NAME.zip

- export PATH=$PATH:$(pwd)/$DISTRIBUTION_NAME/bin

- ballerina version

# Kafka
- KAFKA_VERSION=kafka_2.11-1.1.0

- wget http://www-us.apache.org/dist/kafka/1.1.0/$KAFKA_VERSION.tgz

- tar xzf $KAFKA_VERSION.tgz

- ./$KAFKA_VERSION/bin/zookeeper-server-start.sh -daemon ./$KAFKA_VERSION/config/zookeeper.properties

- ./$KAFKA_VERSION/bin/kafka-server-start.sh -daemon ./$KAFKA_VERSION/config/server.properties

# Ballerina Kafka Connector
- KAFKA_CONNECTOR_VERSION=0.96.1
- KAFKA_CONNECTOR_DISTRIBUTION=wso2-kafka-$KAFKA_CONNECTOR_VERSION

- wget https://github.com/wso2-ballerina/package-kafka/releases/download/v$KAFKA_CONNECTOR_VERSION/$KAFKA_CONNECTOR_DISTRIBUTION.zip

- unzip -q $KAFKA_CONNECTOR_DISTRIBUTION.zip -d $KAFKA_CONNECTOR_DISTRIBUTION

- cp $KAFKA_CONNECTOR_DISTRIBUTION/dependencies/wso2-kafka-package-$KAFKA_CONNECTOR_VERSION.jar $DISTRIBUTION_NAME/bre/lib
- cp -R $KAFKA_CONNECTOR_DISTRIBUTION/balo/wso2 $DISTRIBUTION_NAME/lib/repo

- cd guide

- ballerina init

- ballerina test
