before_install:
- sudo chmod +x install-dependencies.sh
install: ./install-dependencies.sh

script:
- ls
- export PATH=$PATH:$(pwd)/ballerina-0.964.0/bin
- echo $PATH
- ballerina version
- ballerina test guide/restful_service

jdk:
 - oraclejdk8
