# Copyright (c) 2018, WSO2 Inc. (http://wso2.com) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

script:
# Declare STRING variables
- STRING="Downloading Ballerina..."
- STRING1="Downloading ActiveMQ..."

# Declare variable for Ballerina version
- BALLERINA_VERSION="${VERSION:-0.980.2-SNAPSHOT}"
- DISTRIBUTION_NAME=ballerina-platform-$BALLERINA_VERSION

# Declare variable for ActiveMQ version
- ACTIVEMQ_VERSION="apache-activemq-5.15.4"

# Print STRING variable
- echo $STRING

# Download Ballerina dist
- wget https://product-dist.ballerina.io/nightly/$BALLERINA_VERSION/$DISTRIBUTION_NAME.zip

# Unzip the zip file
- unzip -q $DISTRIBUTION_NAME.zip

# Add Ballerina to the path variable
- export PATH=$PATH:$(pwd)/$DISTRIBUTION_NAME/bin

# Print Ballerina version
- ballerina version

# Print STRING1 variable
- echo $STRING1

# Download ActiveMQ
- wget https://archive.apache.org/dist/activemq/5.15.4/$ACTIVEMQ_VERSION-bin.tar.gz

# Untar the tar file
- tar xzf $ACTIVEMQ_VERSION-bin.tar.gz

# Start ActiveMQ
- ./$ACTIVEMQ_VERSION/bin/activemq start

# Copy ActiveMQ jars into Ballerina lib folder
- cp $ACTIVEMQ_VERSION/lib/activemq-client-5.15.4.jar $DISTRIBUTION_NAME/bre/lib
- cp $ACTIVEMQ_VERSION/lib/geronimo-j2ee-management_1.1_spec-1.0.1.jar $DISTRIBUTION_NAME/bre/lib
- cp $ACTIVEMQ_VERSION/lib/hawtbuf-1.11.jar $DISTRIBUTION_NAME/bre/lib

# Change the directory
- cd guide/

# Initialize the Ballerina project
- ballerina init

# Run tests
- ballerina test
