[project]
org-name= "wso2"
version = "1.1.0"
license= ["Apache-2.0"]
authors= ["WSO2"]
keywords= ["ballerina", "integrator", "gmail"]
repository= "https://github.com/wso2/ballerina-integrator"
templates= ["gmail_client_application"]

[dependencies]
