[project]
org-name= "wso2"
version= "0.1.3"
license= ["Apache-2.0"]
authors= ["WSO2"]
keywords= ["ballerina", "integrator", "store", "forward"]
repository= "https://github.com/wso2/ballerina-integrator"
templates= ["message_processor", "message_store"]

[dependencies]

[platform]
target = "java8"

  [[platform.libraries]]
  module = "listener"
  path = "./lib/activemq-client-5.15.9.jar"

  [[platform.libraries]]
  module = "listener"
  path = "./lib/geronimo-j2ee-management_1.1_spec-1.0.1.jar"

  [[platform.libraries]]
  module = "listener"
  path = "./lib/hawtbuf-1.11.jar"
