[project]
org-name= "wso2"
version= "0.1.2"
license= ["Apache-2.0"]
authors= ["WSO2"]
keywords= ["ballerina", "integrator", "backend-for-frontend"]
repository= "https://github.com/wso2/ballerina-integrator"
templates= ["healthcare_management_service"]

[dependencies]
